model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
personality = "pragmatic"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
enabled = false

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"
enabled = false

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"
enabled = false

[plugins."github@openai-curated"]
enabled = true

[features]
codex_hooks = true
